// Ruby Standard Library Detector
// Handles detection of Ruby standard library entities

pub struct RubyStdlibDetector;

impl RubyStdlibDetector {
    // Core modules and classes
    pub const CORE_MODULES: &[&str] = &[
        // Core classes
        "Kernel",
        "Object",
        "Module",
        "Class",
        "BasicObject",
        // Basic types
        "String",
        "Integer",
        "Float",
        "Numeric",
        "Array",
        "Hash",
        "Range",
        "Regexp",
        "Time",
        "Date",
        "DateTime",
        "Symbol",
        "TrueClass",
        "FalseClass",
        "NilClass",
        "Proc",
        "Method",
        "UnboundMethod",
        "Binding",
        "Thread",
        "Fiber",
        "Exception",
        "StandardError",
        "RuntimeError",
        "ArgumentError",
        "IndexError",
        "KeyError",
        "TypeError",
        "NameError",
        "NoMethodError",
        "LoadError",
        "SyntaxError",
        "SystemExit",
        "SystemCallError",
        "IOError",
        "EOFError",
        "LocalJumpError",
        "RangeError",
        "FloatDomainError",
        "ZeroDivisionError",
        "RegexpError",
        "ThreadError",
        "FrozenError",
        "EncodingError",
        "Encoding",
        "Encoding::Converter",
        "Encoding::InvalidByteSequenceError",
        "Encoding::UndefinedConversionError",
        "Encoding::CompatibilityError",
        // Enumerable and Comparable
        "Enumerable",
        "Comparable",
        // IO and File
        "IO",
        "File",
        "Dir",
        "FileTest",
        "FileUtils",
        "Pathname",
        // Math
        "Math",
        "Complex",
        "Rational",
        "BigDecimal",
        "BigMath",
        // Collections
        "Set",
        "SortedSet",
        "Queue",
        "SizedQueue",
        "Thread::Queue",
        "Thread::SizedQueue",
        // Concurrency
        "Mutex",
        "ConditionVariable",
        "Monitor",
        "MonitorMixin",
        "Thread::Mutex",
        "Thread::ConditionVariable",
        // Process
        "Process",
        "Process::Status",
        "Process::Waiter",
        "Process::Tms",
        "Process::UID",
        "Process::GID",
        // Signal
        "Signal",
        "SignalException",
        // System
        "SystemExit",
        "SystemCallError",
        "Errno",
        // Garbage collection
        "GC",
        "ObjectSpace",
        // Marshal
        "Marshal",
        // JSON
        "JSON",
        "JSON::Ext",
        "JSON::Ext::Generator",
        "JSON::Ext::Parser",
        // YAML
        "YAML",
        "Psych",
        // CSV
        "CSV",
        // Logger
        "Logger",
        "Logger::Severity",
        "Logger::LogDevice",
        // URI
        "URI",
        "URI::Generic",
        "URI::HTTP",
        "URI::HTTPS",
        "URI::FTP",
        "URI::LDAP",
        "URI::MailTo",
        "URI::File",
        // Net
        "Net::HTTP",
        "Net::HTTPS",
        "Net::FTP",
        "Net::SMTP",
        "Net::IMAP",
        "Net::POP3",
        "Net::Telnet",
        "Net::SSH",
        "Net::SCP",
        // Socket
        "Socket",
        "Socket::Option",
        "Socket::AncillaryData",
        "Socket::Ifaddr",
        "Socket::Constants",
        "Addrinfo",
        "IPSocket",
        "TCPSocket",
        "TCPServer",
        "UDPSocket",
        "UNIXSocket",
        "UNIXServer",
        "Socket::UDPSource",
        // OpenSSL
        "OpenSSL",
        "OpenSSL::SSL",
        "OpenSSL::X509",
        "OpenSSL::PKey",
        "OpenSSL::Cipher",
        "OpenSSL::Digest",
        "OpenSSL::HMAC",
        "OpenSSL::Random",
        "OpenSSL::BN",
        "OpenSSL::ASN1",
        // Zlib
        "Zlib",
        "Zlib::Deflate",
        "Zlib::Inflate",
        "Zlib::GzipReader",
        "Zlib::GzipWriter",
        "Zlib::GzipFile",
        // Base64
        "Base64",
        // Digest
        "Digest",
        "Digest::MD5",
        "Digest::SHA1",
        "Digest::SHA2",
        "Digest::SHA256",
        "Digest::SHA384",
        "Digest::SHA512",
        // SecureRandom
        "SecureRandom",
        // CGI
        "CGI",
        "CGI::Cookie",
        "CGI::Session",
        "CGI::HtmlExtension",
        // ERB
        "ERB",
        "ERB::Util",
        // REXML
        "REXML",
        "REXML::Document",
        "REXML::Element",
        "REXML::Attribute",
        "REXML::Text",
        "REXML::Comment",
        "REXML::Instruction",
        "REXML::CData",
        "REXML::DocType",
        "REXML::XMLDecl",
        "REXML::Parent",
        "REXML::Child",
        // RDoc
        "RDoc",
        "RDoc::Markup",
        "RDoc::Markup::Parser",
        "RDoc::Markup::Formatter",
        // IRB
        "IRB",
        "IRB::Context",
        "IRB::WorkSpace",
        "IRB::Notifier",
        "IRB::Inspector",
        // Debug
        "Debug",
        "Debug::Inspector",
        "Debug::Tracer",
        // Benchmark
        "Benchmark",
        "Benchmark::Tms",
        // Profiler
        "Profiler__",
        "RubyProf",
        // Tracer
        "Tracer",
        // Coverage
        "Coverage",
        // RubyVM
        "RubyVM",
        "RubyVM::InstructionSequence",
        "RubyVM::AbstractSyntaxTree",
        "RubyVM::MJIT",
        // TracePoint
        "TracePoint",
        // Fiber
        "Fiber",
        "Fiber::Scheduler",
        "Fiber::SchedulerInterface",
        // Ractor
        "Ractor",
        "Ractor::MovedError",
        "Ractor::RemoteError",
        "Ractor::ClosedError",
        "Ractor::IsolationError",
        // Gem
        "Gem",
        "Gem::Specification",
        "Gem::Version",
        "Gem::Requirement",
        "Gem::Dependency",
        "Gem::Platform",
        "Gem::Ext::Builder",
        "Gem::Ext::CmakeBuilder",
        "Gem::Ext::ConfigureBuilder",
        "Gem::Ext::RakeBuilder",
        // Bundler
        "Bundler",
        "Bundler::Dependency",
        "Bundler::Dsl",
        "Bundler::Env",
        "Bundler::Fetcher",
        "Bundler::GemHelper",
        "Bundler::GemVersionPromoter",
        "Bundler::Graph",
        "Bundler::Index",
        "Bundler::Injector",
        "Bundler::Installer",
        "Bundler::LazySpecification",
        "Bundler::LockfileParser",
        "Bundler::MatchPlatform",
        "Bundler::Plugin",
        "Bundler::RemoteSpecification",
        "Bundler::Resolver",
        "Bundler::RubyVersion",
        "Bundler::RubyDsl",
        "Bundler::Runtime",
        "Bundler::Settings",
        "Bundler::SharedHelpers",
        "Bundler::Source",
        "Bundler::Source::Git",
        "Bundler::Source::Path",
        "Bundler::Source::Rubygems",
        "Bundler::SourceList",
        "Bundler::SpecSet",
        "Bundler::StubSpecification",
        "Bundler::UI",
        "Bundler::URICredentialsFilter",
        "Bundler::VersionRanges",
    ];

    // Kernel methods (global functions)
    pub const KERNEL_METHODS: &[&str] = &[
        // Basic I/O
        "puts",
        "print",
        "printf",
        "gets",
        "readline",
        "readlines",
        "p",
        "pp",
        "puts",
        "putc",
        // File operations
        "require",
        "require_relative",
        "load",
        "autoload",
        "autoload?",
        // Object operations
        "raise",
        "fail",
        "catch",
        "throw",
        "eval",
        "instance_eval",
        "class_eval",
        "module_eval",
        "binding",
        "local_variables",
        "instance_variables",
        "class_variables",
        "global_variables",
        // Type conversion
        "to_s",
        "to_i",
        "to_f",
        "to_a",
        "to_h",
        "to_proc",
        "to_str",
        "to_int",
        "to_ary",
        "to_hash",
        "to_io",
        "to_regexp",
        "to_sym",
        "to_r",
        "to_c",
        // Comparison
        "<=>",
        "==",
        "===",
        "eql?",
        "equal?",
        "=~",
        "!~",
        // Boolean
        "nil?",
        "true?",
        "false?",
        "empty?",
        "blank?",
        "present?",
        // Numeric
        "abs",
        "ceil",
        "floor",
        "round",
        "truncate",
        "divmod",
        "div",
        "modulo",
        "remainder",
        "nonzero?",
        "zero?",
        "positive?",
        "negative?",
        "finite?",
        "infinite?",
        "nan?",
        // String
        "length",
        "size",
        "bytesize",
        "empty?",
        "include?",
        "start_with?",
        "end_with?",
        "index",
        "rindex",
        "match",
        "match?",
        "scan",
        "gsub",
        "gsub!",
        "sub",
        "sub!",
        "split",
        "lines",
        "chars",
        "codepoints",
        "bytes",
        "upcase",
        "upcase!",
        "downcase",
        "downcase!",
        "capitalize",
        "capitalize!",
        "swapcase",
        "swapcase!",
        "strip",
        "strip!",
        "lstrip",
        "lstrip!",
        "rstrip",
        "rstrip!",
        "chomp",
        "chomp!",
        "chop",
        "chop!",
        "squeeze",
        "squeeze!",
        "tr",
        "tr!",
        "tr_s",
        "tr_s!",
        "delete",
        "delete!",
        "count",
        "hex",
        "oct",
        "to_i",
        "to_f",
        "to_sym",
        "intern",
        "to_str",
        "inspect",
        "dump",
        // Array
        "[]",
        "[]=",
        "at",
        "fetch",
        "first",
        "last",
        "concat",
        "<<",
        "push",
        "pop",
        "shift",
        "unshift",
        "insert",
        "delete",
        "delete_at",
        "delete_if",
        "keep_if",
        "select",
        "select!",
        "reject",
        "reject!",
        "compact",
        "compact!",
        "flatten",
        "flatten!",
        "shuffle",
        "shuffle!",
        "sample",
        "permutation",
        "combination",
        "product",
        "transpose",
        "zip",
        "cycle",
        "rotate",
        "rotate!",
        "sort",
        "sort!",
        "sort_by",
        "sort_by!",
        "reverse",
        "reverse!",
        "reverse_each",
        "each_index",
        "each_with_index",
        "each_with_object",
        "map",
        "map!",
        "collect",
        "collect!",
        "inject",
        "reduce",
        "partition",
        "group_by",
        "all?",
        "any?",
        "none?",
        "one?",
        "count",
        "sum",
        "max",
        "min",
        "minmax",
        "min_by",
        "max_by",
        "minmax_by",
        "uniq",
        "uniq!",
        "take",
        "take_while",
        "drop",
        "drop_while",
        // Hash
        "keys",
        "values",
        "has_key?",
        "has_value?",
        "key?",
        "value?",
        "include?",
        "member?",
        "fetch",
        "store",
        "default",
        "default=",
        "default_proc",
        "default_proc=",
        "delete",
        "delete_if",
        "keep_if",
        "select",
        "select!",
        "reject",
        "reject!",
        "clear",
        "invert",
        "merge",
        "merge!",
        "update",
        "replace",
        "shift",
        "inspect",
        "to_hash",
        "to_h",
        "to_proc",
        // Enumerable methods
        "each",
        "each_entry",
        "each_slice",
        "each_cons",
        "each_with_index",
        "each_with_object",
        "reverse_each",
        "entries",
        "to_a",
        "to_h",
        "find",
        "detect",
        "find_all",
        "select",
        "reject",
        "collect",
        "map",
        "flat_map",
        "collect_concat",
        "inject",
        "reduce",
        "partition",
        "group_by",
        "first",
        "all?",
        "any?",
        "one?",
        "none?",
        "count",
        "sum",
        "max",
        "min",
        "minmax",
        "min_by",
        "max_by",
        "minmax_by",
        "sort",
        "sort_by",
        "grep",
        "grep_v",
        "zip",
        "take",
        "take_while",
        "drop",
        "drop_while",
        "cycle",
        "chunk",
        "slice_before",
        "slice_after",
        "slice_when",
        "chunk_while",
        // File and IO
        "open",
        "read",
        "write",
        "seek",
        "tell",
        "pos",
        "pos=",
        "eof?",
        "eof",
        "close",
        "closed?",
        "flush",
        "sync",
        "sync=",
        "binmode",
        "binmode?",
        "autoclose=",
        "autoclose?",
        "pid",
        "inspect",
        "to_io",
        "stat",
        "lstat",
        "ftype",
        "atime",
        "mtime",
        "ctime",
        "size",
        "zero?",
        "executable?",
        "readable?",
        "writable?",
        "owned?",
        "grpowned?",
        "setuid?",
        "setgid?",
        "sticky?",
        "pipe?",
        "symlink?",
        "socket?",
        "blockdev?",
        "chardev?",
        "directory?",
        "file?",
        // Time
        "now",
        "at",
        "local",
        "gm",
        "utc",
        "mktime",
        "parse",
        "strptime",
        "year",
        "month",
        "day",
        "hour",
        "min",
        "sec",
        "usec",
        "nsec",
        "subsec",
        "wday",
        "yday",
        "isdst",
        "zone",
        "utc_offset",
        "to_i",
        "to_f",
        "to_r",
        "to_s",
        "inspect",
        "asctime",
        "ctime",
        "strftime",
        "getlocal",
        "getgm",
        "getutc",
        "utc?",
        "gmt?",
        "localtime",
        "gmtime",
        "utc",
        "gmt",
        "sunday?",
        "monday?",
        "tuesday?",
        "wednesday?",
        "thursday?",
        "friday?",
        "saturday?",
        // Math
        "sqrt",
        "cbrt",
        "hypot",
        "sin",
        "cos",
        "tan",
        "asin",
        "acos",
        "atan",
        "atan2",
        "sinh",
        "cosh",
        "tanh",
        "asinh",
        "acosh",
        "atanh",
        "exp",
        "log",
        "log10",
        "log2",
        "frexp",
        "ldexp",
        "erf",
        "erfc",
        "gamma",
        "lgamma",
        // Random
        "rand",
        "srand",
        "bytes",
        "random_number",
        "urandom",
    ];

    // Built-in global functions
    pub const GLOBAL_FUNCTIONS: &[&str] = &[
        "puts",
        "print",
        "printf",
        "gets",
        "readline",
        "readlines",
        "p",
        "pp",
        "require",
        "require_relative",
        "load",
        "autoload",
        "raise",
        "fail",
        "catch",
        "throw",
        "eval",
        "binding",
        "local_variables",
        "instance_variables",
        "class_variables",
        "global_variables",
        "sleep",
        "exit",
        "abort",
        "system",
        "exec",
        "fork",
        "spawn",
        "Process.wait",
        "Process.waitpid",
        "Process.wait2",
        "Process.waitpid2",
        "Process.detach",
        "Process.kill",
        "Process.getpgid",
        "Process.setpgid",
        "Process.getpriority",
        "Process.setpriority",
        "Process.groups",
        "Process.groups=",
        "Process.initgroups",
        "Process.maxgroups",
        "Process.maxgroups=",
        "Process.uid",
        "Process.gid",
        "Process.euid",
        "Process.egid",
        "Process.pid",
        "Process.ppid",
        "Process.getpgrp",
        "Process.setpgrp",
        "Process.getsid",
        "Process.setsid",
        "Process.getrlimit",
        "Process.setrlimit",
        "Process.clock_gettime",
        "Process.clock_getres",
        "Process.times",
        "Process.rusage",
        "rand",
        "srand",
        "rand",
        "srand",
        "Array",
        "Hash",
        "String",
        "Integer",
        "Float",
        "Complex",
        "Rational",
        "BigDecimal",
        "Time",
        "Date",
        "DateTime",
        "Regexp",
        "Range",
        "Struct",
        "OpenStruct",
        "Data",
        "Object",
        "Module",
        "Class",
        "Kernel",
        "BasicObject",
        "Proc",
        "Method",
        "UnboundMethod",
        "Binding",
        "Thread",
        "Fiber",
        "Ractor",
        "Mutex",
        "ConditionVariable",
        "Queue",
        "SizedQueue",
        "Monitor",
        "MonitorMixin",
        "Signal",
        "SignalException",
        "GC",
        "ObjectSpace",
        "Marshal",
        "JSON",
        "YAML",
        "CSV",
        "Logger",
        "URI",
        "Net::HTTP",
        "Socket",
        "OpenSSL",
        "Zlib",
        "Base64",
        "Digest",
        "SecureRandom",
        "CGI",
        "ERB",
        "REXML",
        "RDoc",
        "IRB",
        "Debug",
        "Benchmark",
        "Profiler__",
        "RubyProf",
        "Tracer",
        "Coverage",
        "RubyVM",
        "TracePoint",
        "Gem",
        "Bundler",
    ];

    // Standard library modules (lowercase, as used with `require`)
    pub const STDLIB_REQUIRES: &[&str] = &[
        "json",
        "csv",
        "yaml",
        "net/http",
        "net/https",
        "net/smtp",
        "net/pop",
        "net/imap",
        "net/ftp",
        "uri",
        "openssl",
        "digest",
        "digest/md5",
        "digest/sha1",
        "zlib",
        "gzip",
        "fileutils",
        "pathname",
        "tmpdir",
        "tempfile",
        "file",
        "io",
        "socket",
        "timeout",
        "webrick",
        "rack",
        "logger",
        "optparse",
        "shellwords",
        "base64",
        "erb",
        "rexml",
        "nokogiri",
        "cgi",
        "securerandom",
        "benchmark",
        "mutex_m",
        "monitor",
        "thread",
        "fiber",
        "queue",
        "set",
        "forwardable",
        "singleton",
        "delegate",
        "observer",
        "ostruct",
        "date",
        "time",
        "bigdecimal",
        "complex",
        "rational",
        "matrix",
        "prime",
        "cmath",
        "abbrev",
        "ansi",
        "resolv",
        "ipaddr",
        "getoptlong",
        "optparse",
        "shellwords",
        "word_wrap",
        "pp",
        "prettyprint",
        "irb",
        "ripper",
        "rdoc",
        "test/unit",
        "minitest",
        "rspec",
        "rake",
        "bundler",
        "rubygems",
        "gem",
        "did_you_mean",
        "error_highlight",
        "debug",
        "coverage",
        "tracepoint",
        "gc",
        "objspace",
        "weakref",
        "continuation",
        "generator",
        "erb",
    ];
}

// Generate simple containment check functions
impl_list_checker!(
    RubyStdlibDetector,
    [
        (CORE_MODULES, is_core_module),
        (KERNEL_METHODS, is_kernel_method),
        (GLOBAL_FUNCTIONS, is_global_function),
        (STDLIB_REQUIRES, is_stdlib_require),
    ]
);

impl RubyStdlibDetector {
    /// Check if a qualified path is from stdlib
    pub fn is_stdlib_path(path: &str) -> bool {
        // Ruby uses :: as namespace separator
        // Check for exact match
        if Self::is_core_module(path) {
            return true;
        }

        // Check if any core module starts with this path as prefix
        for &module in Self::CORE_MODULES {
            if module.starts_with(&format!("{}::", path)) {
                return true;
            }
        }

        // Check first component
        let first_component = path.split("::").next().unwrap_or("");
        Self::is_core_module(first_component)
    }

    /// Check if a call is to stdlib
    pub fn is_stdlib_call(call_name: &str) -> bool {
        // Check for direct global function
        if Self::is_global_function(call_name) {
            return true;
        }

        // Check for Kernel method
        if Self::is_kernel_method(call_name) {
            return true;
        }

        // Check for qualified path (e.g., File.open, Time.now, Net::HTTP.get)
        if call_name.contains("::") || call_name.contains('.') {
            // Extract the module path part (without the method name)
            let module_path = if call_name.contains('.') {
                call_name.split('.').next().unwrap_or("")
            } else {
                call_name
            };

            // Check if the module path is from stdlib
            if Self::is_stdlib_path(module_path) {
                return true;
            }

            // Fallback: check the first component
            let parts: Vec<&str> = if call_name.contains("::") {
                call_name.split("::").collect()
            } else {
                call_name.split('.').collect()
            };

            if !parts.is_empty() {
                let receiver = parts[0];
                if Self::is_core_module(receiver) {
                    return true;
                }
            }
        }

        false
    }
}

// Generate is_stdlib_by_type using simple macro
impl_stdlib_by_type_simple!(
    RubyStdlibDetector,
    [
        DirectCall,
        InstanceMethodCall,
        StaticMethodCall,
        ChainedMethodCall,
        ConstructorCall,
        CallbackCall,
        GenericCall,
    ]
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_core_module() {
        assert!(RubyStdlibDetector::is_core_module("String"));
        assert!(RubyStdlibDetector::is_core_module("Array"));
        assert!(RubyStdlibDetector::is_core_module("Hash"));
        assert!(!RubyStdlibDetector::is_core_module("MyClass"));
    }

    #[test]
    fn test_is_kernel_method() {
        assert!(RubyStdlibDetector::is_kernel_method("puts"));
        assert!(RubyStdlibDetector::is_kernel_method("require"));
        assert!(!RubyStdlibDetector::is_kernel_method("my_method"));
    }

    #[test]
    fn test_is_global_function() {
        assert!(RubyStdlibDetector::is_global_function("puts"));
        assert!(RubyStdlibDetector::is_global_function("require"));
        assert!(RubyStdlibDetector::is_global_function("Array"));
        assert!(!RubyStdlibDetector::is_global_function("my_function"));
    }

    #[test]
    fn test_is_stdlib_path() {
        assert!(RubyStdlibDetector::is_stdlib_path("File"));
        assert!(RubyStdlibDetector::is_stdlib_path("Time::now"));
        assert!(RubyStdlibDetector::is_stdlib_path("Net::HTTP"));
        assert!(!RubyStdlibDetector::is_stdlib_path("MyModule::MyClass"));
    }

    #[test]
    fn test_is_stdlib_call() {
        assert!(RubyStdlibDetector::is_stdlib_call("puts"));
        assert!(RubyStdlibDetector::is_stdlib_call("File.open"));
        assert!(RubyStdlibDetector::is_stdlib_call("Time.now"));
        assert!(RubyStdlibDetector::is_stdlib_call("Net::HTTP.get"));
        assert!(!RubyStdlibDetector::is_stdlib_call("my_function"));
        assert!(!RubyStdlibDetector::is_stdlib_call("MyClass.method"));
    }
}
