//! FFI helper functions used by the `declare_plugin!` macro.
//!
//! These are not part of the public API and may change without notice.

use std::ffi::{c_char, CStr, CString};

use cce_plugin::PluginError;

/// Run `f`, converting any panic into a `PluginError::ExecutionFailed`.
///
/// Every `extern "C"` export generated by `declare_plugin!` runs user
/// code through this guard so a panic never unwinds across the FFI
/// boundary (which is undefined behaviour). Panics are reported back to
/// the host as a normal FFI error result.
pub fn catch_unwind<F, T>(f: F) -> Result<T, PluginError>
where
    F: FnOnce() -> Result<T, PluginError>,
{
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(f))
        .unwrap_or_else(|_| Err(PluginError::ExecutionFailed("Plugin panicked".to_string())))
}

/// Map a [`PluginError`] to the `error_type` string carried in the FFI
/// result envelope. The host restores the concrete `PluginError` variant
/// from this string.
pub fn error_type_str(err: &PluginError) -> &'static str {
    match err {
        PluginError::ScriptError(_) => "script",
        PluginError::Timeout => "timeout",
        PluginError::InvalidOutput(_) => "invalid_output",
        PluginError::LogicError(_) => "logic",
        PluginError::ResourceError(_) => "resource",
        PluginError::CircuitBroken => "circuit_broken",
        PluginError::NotFound(_) => "not_found",
        PluginError::ExecutionFailed(_) => "execution_failed",
    }
}

/// Serialize a [`PluginError`] into the FFI error envelope:
/// `{"result":"error","message":"...","error_type":"..."}`.
pub fn error_json(err: &PluginError) -> String {
    let msg = err.to_string();
    let escaped = msg.replace('\\', "\\\\").replace('"', "\\\"");
    format!(
        r#"{{"result":"error","message":"{}","error_type":"{}"}}"#,
        escaped,
        error_type_str(err)
    )
}

/// Convert a `PluginError` to a heap-allocated C string.
pub fn error_to_c_string(err: &PluginError) -> *mut c_char {
    let json = error_json(err);
    CString::new(json)
        .unwrap_or_else(|_| {
            CString::new(error_json(&PluginError::InvalidOutput(
                "Error message contained null byte".to_string(),
            )))
            .unwrap()
        })
        .into_raw()
}

/// Convert a `Result<Option<V>, PluginError>` to a heap-allocated C string
/// containing the JSON FFI result.
pub fn result_to_c_string<V: serde::Serialize>(
    result: &Result<Option<V>, PluginError>,
) -> *mut c_char {
    let json = match result {
        Ok(Some(val)) => {
            let value_json = serde_json::to_string(val).unwrap_or_else(|e| {
                error_json(&PluginError::InvalidOutput(format!("Serialize error: {e}")))
            });
            format!(r#"{{"result":"ok","value":{}}}"#, value_json)
        }
        Ok(None) => r#"{"result":"none"}"#.to_string(),
        Err(err) => error_json(err),
    };
    CString::new(json)
        .unwrap_or_else(|_| {
            CString::new(error_json(&PluginError::InvalidOutput(
                "JSON contained null byte".to_string(),
            )))
            .unwrap()
        })
        .into_raw()
}

/// Convert a `Result<Vec<V>, PluginError>` to a heap-allocated C string
/// containing the JSON FFI result. On success the `value` is the
/// serialized array.
pub fn vec_result_to_c_string<V: serde::Serialize>(
    result: &Result<Vec<V>, PluginError>,
) -> *mut c_char {
    let json = match result {
        Ok(vals) => {
            let value_json = serde_json::to_string(vals).unwrap_or_else(|e| {
                error_json(&PluginError::InvalidOutput(format!("Serialize error: {e}")))
            });
            format!(r#"{{"result":"ok","value":{}}}"#, value_json)
        }
        Err(err) => error_json(err),
    };
    CString::new(json)
        .unwrap_or_else(|_| {
            CString::new(error_json(&PluginError::InvalidOutput(
                "JSON contained null byte".to_string(),
            )))
            .unwrap()
        })
        .into_raw()
}

/// Convert a `Result<Option<Vec<V>>, PluginError>` to a heap-allocated C
/// string. `Ok(None)` becomes the `{"result":"none"}` envelope.
pub fn opt_vec_result_to_c_string<V: serde::Serialize>(
    result: &Result<Option<Vec<V>>, PluginError>,
) -> *mut c_char {
    let json = match result {
        Ok(Some(vals)) => {
            let value_json = serde_json::to_string(vals).unwrap_or_else(|e| {
                error_json(&PluginError::InvalidOutput(format!("Serialize error: {e}")))
            });
            format!(r#"{{"result":"ok","value":{}}}"#, value_json)
        }
        Ok(None) => r#"{"result":"none"}"#.to_string(),
        Err(err) => error_json(err),
    };
    CString::new(json)
        .unwrap_or_else(|_| {
            CString::new(error_json(&PluginError::InvalidOutput(
                "JSON contained null byte".to_string(),
            )))
            .unwrap()
        })
        .into_raw()
}

/// Read a `*const c_char` into a Rust `&str`.
///
/// # Safety
///
/// `ptr` must be a valid pointer to a null-terminated C string.
pub unsafe fn read_c_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {
    if ptr.is_null() {
        return Err("Null pointer received".to_string());
    }
    unsafe { CStr::from_ptr(ptr) }
        .to_str()
        .map_err(|e| format!("Invalid UTF-8: {}", e))
}
